# Generated by Django 4.2.7 on 2023-12-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="tag",
            field=models.ManyToManyField(blank=True, to="base.tag"),
        ),
    ]
